# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    tags:
    - "[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Build
      shell: powershell
      run: dotnet publish Remnant2SaveAnalyzer\Remnant2SaveAnalyzer.csproj -c Release --self-contained -r win-x64 "/p:Version=$env:TAG" "/p:AssemblyVersion=$env:TAG"
      env:
        TAG: ${{ github.ref_name }}
    - name: Create release archive
      shell: powershell
      run: |
        7z a "Remnant2SaveAnalyzer-$env:TAG.zip" .\Remnant2SaveAnalyzer\bin\Release\net8.0-windows7.0\win-x64\publish\*
      env:
        TAG: ${{ github.ref_name }}
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: Remnant2SaveAnalyzer-${{ github.ref_name }}.zip
        body: "[CHANGELOG.md](CHANGELOG.md)"
